solution for CounterButton
js-tasks-ru/vue-20210119_krakens-921 pull request #2
Opened 2021-01-26 10:15 UTC by KRaKeNS-B

2021-01-26 11:18 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2021-01-27 10:50 UTC, ShGKme requested changes
Требуется избавиться от вызова методов в шаблоне и немного поправить работу с изображением.

2021-01-27 10:50 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +      :style="`--bg-url: url(${meetupImageUrl})`"
Если изображения у митапа нет, то этот стиль может сбить стили по умолчанию...
Требуется, если изображения нет, не добавлять никаких стилей, не переопределять `--bg-url`.

2021-01-27 10:50 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <img class="icon" alt="icon" :src="`/assets/icons/icon-${getAgendaIcon(agenda.type)}.svg`" />
Лучше избегать вызова методов в шаблоне.

Здесь может быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне). Вычисляемые свойства же будут перевычисляться  только тогда, когда изменяются свойства, от которых они зависят. Другими словами можно сказать, что computed - кэшируется.

Хотя этот метод очень простой и не создаст заметных проблем с производительностью, лучше в начале их избегать.

2021-01-27 10:50 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
>    },
Эти два метода просто обращаются к двум объектам и больше не осуществляют никакой работы.
Вместо добавления для этого методов, лучше добавить эти объекты в контекст компонента, либо заранее подготовить данные митапа.

2021-01-27 12:30 UTC, KRaKeNS-B commented on 01-basics/02-MeetupPageDraft/index.html
> +      :style="`--bg-url: url(${meetupImageUrl})`"
Согласен, не учел, переделаю в computed

2021-01-27 12:37 UTC, KRaKeNS-B commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <img class="icon" alt="icon" :src="`/assets/icons/icon-${getAgendaIcon(agenda.type)}.svg`" />
На сколько я понял, выражения и вызов метода пересчитываются при каждом рендеринге, так что не вижу смысла на него менять. Вызов метода хотя бы прямо говорит нам какие данные мы туда передаем.
Можно добавить подготовку нового массива с нужными данными, но не знаю на сколько это имеет смысл для таких вычислений. Да и при изменении любого значения в массиве будет пересчет всего свойства.
Идеальный вариант вынести agenda в отдельный компонент и там уже в computed все преобразовать

2021-01-27 12:39 UTC, KRaKeNS-B commented on 01-basics/02-MeetupPageDraft/script.js
>    },
Да, эти методы перенесу в computed

2021-01-27 18:50 UTC, ShGKme requested changes
Требуется небольшое изменение

2021-01-27 18:50 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +    },
Если у митапа нет изображения, здесь получится пустой некорректный стиль, который собьёт изображение по умолчанию. Требуется сделать проверку, и не добавлять свойство, если изображение отсутствует (`this.meetup.imageId === null`).

2021-01-27 18:51 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +    },
Вы перенесли выражение в вычисляемое свойство, но ничего не изменилось, просто это значение перешло в вычисляемое свойство

2021-01-27 19:15 UTC, KRaKeNS-B commented on 01-basics/02-MeetupPageDraft/script.js
> +    },
Блин, точно

2021-01-27 19:19 UTC, ShGKme approved these changes
Принято 👍

2021-01-27 19:19 UTC, merged